### ISSUE TITLE
making scalingEditTool the default one

### ISSUE THREAD

**Issue by typemytype** [klaavo/scalingEditTool#3]
by setting `setActiveEventTool('ScalingEditTool')` you activate the tool as default one when a glyph window the first time pops up. This could be confusing for users.

https://github.com/klaavo/scalingEditTool/blob/master/ScalingEditTool.roboFontExt/lib/scalingEditToolExt.py#L229

and this is brought up a small ui bug in RF :) as the segmented toolbar control didnt show the correct active tool.

maybe reconsider to call `setActiveEventTool` while initiating the tool

thanks

**Comment by klaavo** [comment]
Hi Fred!
I removed the setActiveEventTool altogether. I guess I had added it trying to work around the same issue without realizing it's a bug. When installing a tool, any tool that is first in the menu gets selected, but the currently active tool stays active.
Thanks!
